"""create tables

Revision ID: 4f087dbc68c7
Revises: 
Create Date: 2023-10-28 00:13:54.840329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4f087dbc68c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_records')
    op.add_column('patients', sa.Column('patient_id', sa.Integer(), nullable=False))
    op.add_column('patients', sa.Column('primary_doctor_id', sa.Integer(), nullable=False))
    op.alter_column('patients', 'last_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.create_foreign_key(None, 'patients', 'doctors', ['primary_doctor_id'], ['doctor_id'])
    op.drop_column('patients', 'gender')
    op.drop_column('patients', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('patients', sa.Column('gender', mysql.VARCHAR(length=10), nullable=False))
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.alter_column('patients', 'last_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('patients', 'primary_doctor_id')
    op.drop_column('patients', 'patient_id')
    op.create_table('medical_records',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagnosis', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('treatment', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('admission_date', sa.DATE(), nullable=False),
    sa.Column('discharge_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='medical_records_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
